# service:
name: api-log-processor
description: Service to process request-response (or network flow) logs from Kafka topic.

kafka:
  config:
    bootstrapServers: broker:29092
    streamsProperties:
      application.id: "your-application-id"
      default.key.serde: "org.apache.kafka.common.serialization.Serdes$StringSerde"
      default.value.serde: "org.apache.kafka.common.serialization.Serdes$StringSerde"
      state.dir: "/tmp/kafka-streams"
      consumer:
        max.poll.records: 500
        session.timeout.ms: 10000
      producer:
        acks: "all"
        retries: 3
        batch.size: 16384
        linger.ms: 1
      adminClient:
        retries: 5
        request.timeout.ms: 30000
    connectProperties:
      group.id: "eventception-connect"
      key.converter: org.apache.kafka.connect.storage.StringConverter
      value.converter: org.apache.kafka.connect.json.JsonConverter
    authentication:
      sasl.mechanism: "PLAIN"
      security.protocol: "SASL_PLAINTEXT"
      sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username='admin' password='admin-secret';"

topology:
  name: api-cdc-pipeline
  input:
    topics: "api-logs-.*" # Regex pattern to subscribe to input topics
  subTopologies:
  - name: orders
    processors:
      - type: CelFilter
        name: orderfilter
        celExpression: "request.path == '/orders' && (response.status == 200 || response.status == 201)"
      - type: JSONTransform
        name: ordertransform
        transform:
          key: '$join([$substring(request.path, 1), "-", request.body.order_id])'
          value: '{"specversion": "1.0", "action": request.method="POST" ? "create-order": request.method="PUT" ? "update-order" : "unkown", "source": client.ip, "id": request.body.order_id, "orderplaced": $fromMillis(request.time), "orderprocessed": response.headers.date, "order_quantity": request.body.quantity}'
          # value: '{"specversion": "1.0", "action": request.method="POST" ? "create-order": request.method="PUT" ? "update-order" : "unkown", "source": client.ip, "id": request.body.order_id, "orderplaced": $fromMillis(request.time, "[FNn,3], [D01] [MNn,3] [Y0001] [h01]:[m01]:[s01] [z]"), "orderprocessed": response.headers.date}'
      - type: ChangeDataCapture
        name: ordercdc
        keyLookupExpression: "request.id" # Not implemented
    output:
      topic: "orders-cdc"
      dlq: "orders-cdc-dlq"
  - name: users
    processors:
      - type: CelFilter
        name: userfilter
        celExpression: "request.path == '/users' && (response.status == 200 || response.status == 201)"
      - type: JSONTransform
        name: usertransform
        transform:
          key: '$join([$substring(request.path, 1), "-", request.body.user_id])'
          value: '{"specversion": "1.0", "action": request.method="POST" ? "create-user": request.method="PUT" ? "update-user" : "unkown", "source": client.ip, "id": request.body.user_id, "userplaced": $fromMillis(request.time), "userprocessed": response.headers.date, "user_age": request.body.age}'
      - type: ChangeDataCapture
        name: usercdc
        keyLookupExpression: "request.id" # Not implemented
    output:
      topic: "users-cdc"
      dlq: "users-cdc-dlq"

# connectors:
#   - type: WebhookSink
#     name: mylittleservice
#     config:
#       url: http://kong:8000/demo
#       headers: "Content-Type:application/json" # Comma separated
#       authentication:
#         type: basic # none, basic, bearer
#         username: demouser
#         password: OpenSesame